apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-deploy-inventory-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy
  params:
  - name: deployment-name
    value: pipelines-vote-api
  - name: git-url
    value: https://github.com/gvenkatx/app-mod-pipeline.git
  - name: git-revision
    value: ocp-4.7
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi